/*\
title: $:/plugins/tobibeer/plantuml/widget.js
type: application/javascript
module-type: widget

A widget to render plantuml

@preserve
\*/
(function(){"use strict";var t=require("$:/core/modules/widgets/widget.js").widget;var e=function(t,e){this.initialise(t,e)};e.prototype=new t;e.prototype.render=function(t,e){this.parentDomNode=t;this.computeAttributes();this.execute();var i,s,u,r,a=this.node,l=[],n=function(t){var e=t;while(e){if(e.nodeName&&(e.nodeName==="a"||e.nodeName==="button")){return 1}e=e.parentNode}return 0};switch(this.output){case"src":a.type="element";a.tag="pre";a.children=[{type:"text",text:this.source}];l.push(a);break;case"txt":a.type="element";a.tag="iframe";a.attributes.src={type:"string",value:$tw.utils.plantuml.encodePlantUML(this.source,this.output)};i=a.attributes["class"]?a.attributes["class"].value+" ":"";a.attributes["class"]={type:"string",value:i+"tc-plantuml-txt"};s=a.attributes.height?"height:"+a.attributes.height.value+";":"";r=a.attributes.width?"width:"+a.attributes.width.value+";":"";if(s||r){a.attributes.style={type:"string",value:s+r}}if(a.attributes.tooltip&&!this.edit){l.push({type:"element",tag:"div",attributes:{"class":{type:"string",value:"tc-plantuml-txt-title"}},children:[{type:"text",text:a.attributes.tooltip.value}]})}l.push(a);break;default:a.attributes.source={type:"string",value:$tw.utils.plantuml.encodePlantUML(this.source,this.output)};l.push(a)}if(this.edit&&!n(this.parentDomNode)){u={type:"element",tag:"a",attributes:{"class":{type:"string",value:"tc-plantuml-edit tc-tiddlylink-external"},target:{type:"string",value:"_blank"},href:{type:"string",value:$tw.utils.plantuml.encodePlantUML(this.source,"edit")}}};if(this.output==="txt"){u.children=[{type:"text",text:this.wiki.getTextReference("$:/plugins/tobibeer/plantuml/lingo/edit-link")+(a.attributes.tooltip?a.attributes.tooltip.value:"")}];l.unshift(u)}else{u.children=l;l=[u]}}this.makeChildWidgets(l);this.renderChildren(this.parentDomNode,e)};e.prototype.execute=function(){var t=this;this.source=this.getAttribute("source","");this.output=this.getAttribute("output","svg");this.edit=this.getAttribute("edit");if(this.edit===undefined){this.edit=this.wiki.getTextReference("$:/plugins/tobibeer/plantuml/defaults/edit")}this.edit=["yes","true"].indexOf((this.edit||"").toLowerCase())>=0;this.node={type:"image",attributes:{}};["width","height","class","tooltip","alt"].map(function(e){var i=t.getAttribute(e);if(i!==undefined){t.node.attributes[e]={type:"string",value:i}}})};e.prototype.refresh=function(){var t=this.computeAttributes();if(t.source||t.width||t.height||t["class"]||t.tooltip||t.output||t.edit){this.refreshSelf();return true}else{return false}};exports.plantuml=e})();